#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/saransh1337/Developer/SDKs/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.1.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=U05BUEdSVUJfRU5WPWRldg==,U1VQQUJBU0VfVVJMPWh0dHBzOi8vaXlmaG5zemJud29qdXJ4amRsbnouc3VwYWJhc2UuY28=,U1VQQUJBU0VfQU5PTl9LRVk9ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1sNVptaHVjM3BpYm5kdmFuVnllR3BrYkc1Nklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTnprek5qQXlORGNzSW1WNGNDSTZNakE1TkRrek5qSTBOMzAuMERPbExORkVfdUZjSkRRb2NVNm8xSnFieVllNFQtV2dNamM4RjlRSkw2VQ==,RkxVVFRFUl9WRVJTSU9OPTMuNDQuMA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NTU5ZmZhM2Y3NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NGM1MjVkYWM1ZQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4w"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile/.dart_tool/package_config.json"
