#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/saransh1337/Developer/SDKs/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/var/folders/2h/3nps31kj6qxdvwbm3nkkd7580000gn/T/flutter_tools.jaasQW/flutter_test_listener.kayLuh/listener.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.1.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=U05BUEdSVUJfRTJFPXRydWU=,U05BUEdSVUJfRTJFX0JBQ0tFTkQ9bW9jaw==,U05BUEdSVUJfRTJFX0FVVEg9cGFzc3dvcmQ=,TUFSS0VUSU5HX0FSVF9ESVI9L1VzZXJzL3NhcmFuc2gxMzM3L0RldmVsb3Blci9Qcm9qZWN0cy9TbmFwR3J1YiBtb25vcmVwby9hcHBzL21vYmlsZS9tYXJrZXRpbmcvaWxsdXN0cmF0aW9ucw==,RkxVVFRFUl9WRVJTSU9OPTMuNDQuMA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049NTU5ZmZhM2Y3NQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NGM1MjVkYWM1ZQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4w,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/saransh1337/Developer/Projects/SnapGrub monorepo/apps/mobile/.dart_tool/package_config.json"
